from __future__ import annotations

import json
import shlex
import shutil
import subprocess
from pathlib import Path


def detect_godot() -> dict:
    for name in ("godot", "godot4", "Godot"):
        path = shutil.which(name)
        if path:
            return {"available": True, "path": path}
    return {"available": False, "path": None}


def build_import_recommendations(profile: str, delivery_report: dict | None = None) -> dict:
    if profile not in {"prop", "environment", "character"}:
        raise ValueError("profile must be prop, environment, or character")

    animation_import = profile == "character"
    profile_rules = {
        "prop": {
            "animationFps": 30,
            "trimming": True,
            "removeImmutableTracks": True,
            "preferStaticScene": True,
            "navigationCandidate": False,
        },
        "environment": {
            "animationFps": 30,
            "trimming": True,
            "removeImmutableTracks": True,
            "preferStaticScene": True,
            "navigationCandidate": True,
        },
        "character": {
            "animationFps": 60,
            "trimming": False,
            "removeImmutableTracks": False,
            "preferStaticScene": False,
            "navigationCandidate": False,
        },
    }[profile]

    recommendations = {
        "sceneImport": {
            "format": "glTF 2.0 / GLB",
            "useNameSuffixes": True,
            "useNodeTypeSuffixes": True,
            "generateTangentsIfMissing": True,
        },
        "animation": {
            "import": animation_import,
            "fps": profile_rules["animationFps"],
            "trimming": profile_rules["trimming"],
            "removeImmutableTracks": profile_rules["removeImmutableTracks"],
        },
        "profile": {
            "preferStaticScene": profile_rules["preferStaticScene"],
            "navigationCandidate": profile_rules["navigationCandidate"],
        },
        "textures": {
            "preferEmbeddedOrProjectLocal": True,
            "remoteUrisAllowed": False,
        },
    }

    if delivery_report:
        scene = delivery_report.get("scene", {})
        if scene.get("godotNameSuffixes"):
            recommendations["sceneImport"]["useNameSuffixes"] = True
        if not scene.get("animations"):
            recommendations["animation"]["import"] = False

    return recommendations


def prepare_godot_handoff(
    source_glb: Path,
    output_dir: Path,
    *,
    profile: str,
    delivery_report: dict | None = None,
    asset_manifest: dict | None = None,
    allow_unvalidated: bool = False,
) -> dict:
    source_glb = Path(source_glb)
    output_dir = Path(output_dir)
    if not source_glb.is_file():
        raise ValueError(f"source GLB does not exist: {source_glb}")
    if source_glb.suffix.lower() != ".glb":
        raise ValueError("Godot handoff expects a .glb file")
    if not allow_unvalidated:
        if delivery_report is None:
            raise ValueError("validated Godot delivery report is required")
        if delivery_report.get("ready") is not True:
            raise ValueError("Godot delivery report is not ready")

    project_dir = output_dir / "godot-handoff"
    asset_dir = project_dir / "assets"
    asset_dir.mkdir(parents=True, exist_ok=True)

    destination = asset_dir / source_glb.name
    shutil.copy2(source_glb, destination)

    project_file = project_dir / "project.godot"
    project_file.write_text(
        '; Generated by asset-forge\n'
        'config_version=5\n\n'
        '[application]\n'
        'config/name="Asset Forge Handoff"\n\n'
        '[rendering]\n'
        'renderer/rendering_method="gl_compatibility"\n',
        encoding="utf-8",
    )

    recommendations = build_import_recommendations(profile, delivery_report)

    provenance = None
    if asset_manifest is not None:
        source = asset_manifest.get("source", {})
        license_data = asset_manifest.get("license", {})
        provenance = {
            "assetId": asset_manifest.get("id"),
            "project": asset_manifest.get("project"),
            "assetType": asset_manifest.get("type"),
            "importance": asset_manifest.get("importance"),
            "source": {
                "mode": source.get("mode") if isinstance(source, dict) else None,
                "uri": source.get("uri") if isinstance(source, dict) else None,
                "author": source.get("author") if isinstance(source, dict) else None,
            },
            "license": {
                "id": license_data.get("id") if isinstance(license_data, dict) else None,
                "commercialUse": license_data.get("commercialUse") if isinstance(license_data, dict) else None,
                "derivatives": license_data.get("derivatives") if isinstance(license_data, dict) else None,
                "attributionRequired": license_data.get("attributionRequired") if isinstance(license_data, dict) else None,
            },
        }

    manifest = {
        "engine": "Godot 4",
        "profile": profile,
        "source": str(source_glb),
        "asset": "res://assets/" + destination.name,
        "deliveryReady": bool(delivery_report.get("ready")) if delivery_report else None,
        "importRecommendations": recommendations,
        "provenance": provenance,
        "files": {
            "project": str(project_file),
            "asset": str(destination),
        },
    }

    manifest_path = project_dir / "handoff.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    readme = project_dir / "README.md"
    readme.write_text(
        "# Godot 4 asset handoff\n\n"
        "This folder is generated by asset-forge.\n\n"
        f"- Asset: `res://assets/{destination.name}`\n"
        f"- Profile: `{profile}`\n"
        "- Open this folder as a Godot project or run headless import validation.\n"
        "- Review `handoff.json` before integrating the asset into the consuming game project.\n"
        "- Preserve provenance/license metadata when moving this asset to another repository.\n",
        encoding="utf-8",
    )

    return {
        "projectDir": str(project_dir),
        "projectFile": str(project_file),
        "asset": str(destination),
        "manifest": str(manifest_path),
        "readme": str(readme),
        "recommendations": recommendations,
    }


def godot_import_command(executable: str, project_dir: Path) -> list[str]:
    return [
        executable,
        "--headless",
        "--path",
        str(project_dir),
        "--import",
    ]


def validate_godot_handoff(project_dir: Path, executable: str | None = None) -> dict:
    project_dir = Path(project_dir)
    if not (project_dir / "project.godot").is_file():
        raise ValueError("project.godot is missing from handoff directory")

    detected = detect_godot()
    chosen = executable or detected["path"]
    if not chosen:
        return {
            "available": False,
            "passed": None,
            "command": None,
            "returnCode": None,
            "stdout": "",
            "stderr": "",
        }

    command = godot_import_command(chosen, project_dir)
    completed = subprocess.run(
        command,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return {
        "available": True,
        "passed": completed.returncode == 0,
        "command": " ".join(shlex.quote(part) for part in command),
        "returnCode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }
